# reference: https://github.com/mattn/efm-langserver
version: 2
root-markers:
  - .git/
lint-debounce: 1s
commands:
  - command: nvim
    arguments:
      - ${INPUT}

tools:
  python-black: &python-black
    format-command: 'black -S -t py37 -l 79 --quiet -'
    format-stdin: true

  python-isort: &python-isort
    format-command: 'isort -m 3 --trailing-comma --use-parentheses --honor-noqa --quiet -'
    format-stdin: true

  python-pylint: &python-pylint
    lint-command: 'pylint --rcfile=.pylintrc --output-format text --score no --msg-template {path}:{line}:{column}:{C}:{msg} ${INPUT}'
    lint-stdin: false
    lint-formats:
      - '%f:%l:%c:%t:%m'

  sh-shellcheck: &sh-shellcheck
    lint-command: 'shellcheck -f gcc -x'
    lint-source: 'shellcheck'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  sh-shfmt: &sh-shfmt
    format-command: 'shfmt -ci -s -bn'
    format-stdin: true

  lua-lua-format: &lua-lua-format
    format-command: 'lua-format -i'
    format-stdin: true

languages:
  python:
    - <<: *python-black
    - <<: *python-isort
    - <<: *python-pylint

  sh:
    - <<: *sh-shellcheck
    - <<: *sh-shfmt

  lua:
    - <<: *lua-lua-format
