#!/bin/bash

# The modifier to activate the shortcuts below is `<Control> x`.

while read file
do
        case "$1" in
        "p")
                wal -n -i "$file" && notify-send "Changed pywal theme using color palette from $file.";;
        "w")
				feh --bg-fill "$file" && notify-send "Changed wallpaper to $file." ;;
        esac
done
