#!/bin/bash

# CHECK - below is not necessary anymore, it is handled by autorandr:
# if [[ $(xrandr -q | grep 'HDMI-1 connected' | grep '2560') ]]; then
#     /storage/src/dot_files/.screenlayout/cosmos/internal-and-external.sh &
# else
#     /storage/src/dot_files/.screenlayout/cosmos/internal.sh &
# fi

# if [[ $(xrandr -q | grep 'HDMI-1 connected' | grep '2560') ]]; then
#     bspc monitor eDP-1 -d 1 2 3 4 5 &
#     bspc monitor HDMI-1 -d 6 7 8 9 0 &
# fi
bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 0 &

# /storage/src/dot_files/tiling-window-managers/scripts/bspwm-monitors-setup.sh &

#BSPC Settings
bspc config border_width 4
bspc config window_gap 12
bspc config top_padding 30
bspc config bottom_padding 2
bspc config left_padding 10
bspc config right_padding 10
bspc config single_monocle false
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer false
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_slide
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

#Colors
DARK_COLOR="#000000"
ACCENT_COLOR="#9d0006"
ALERT_COLOR="#ffca3a"
bspc config normal_border_color $DARK_COLOR
bspc config active_border_color $ACCENT_COLOR
bspc config focused_border_color $ACCENT_COLOR
bspc config presel_feedback_color $ACCENT_COLOR
bspc config urgent_border_color $ALERT_COLOR

# bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a google-chrome desktop='^4' follow=on
bspc rule -a Cheatsheet state=fullscreen follow=on
bspc rule -a zoom desktop='^4' follow=on
# bspc rule -a mplayer2 state=floating center=true
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
# bspc rule -a Pavucontrol state=floating rectangle=789x512+264+130

echo -e "before autostart..."
/storage/src/dot_files/tiling-window-managers/scripts/autostart.sh &
echo -e "after autostart..."
