#!/bin/bash

echo -e "before autostart..."

# autostart.sh is at my "devops/bin" repository
autostart.sh &

echo -e "after autostart..."

# bspc monitor DisplayPort-1 -d 1 2 3 4 5
if [[ $HOSTNAME == mobpi ]]; then
    bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9 10
else
    bspc monitor HDMI-1 -d 1 2 3 4 5
    bspc monitor eDP-1 -d 6 7 8 9 10
    # bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9 10
fi

echo -e "Defined monitor..."

#BSPC Settings
bspc config border_width 2
bspc config window_gap 12
bspc config top_padding 30
bspc config bottom_padding 10
bspc config left_padding 10
bspc config right_padding 10
bspc config single_monocle false
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer false
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_slide
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

#Colors
bspc config normal_border_color "#000000"
bspc config active_border_color "#eee5e9"
bspc config focused_border_color "#eee5e9"
bspc config presel_feedback_color "#53a77c"
bspc config urgent_border_color "#ffca3a"

# bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a google-chrome desktop='^4' follow=on
bspc rule -a Cheatsheet state=fullscreen follow=on
bspc rule -a zoom desktop='^4' follow=on
# bspc rule -a mplayer2 state=floating center=true
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
# bspc rule -a Pavucontrol state=floating rectangle=789x512+264+130
