#!/bin/bash

echo -e "before autostart..."

/storage/src/dot_files/tiling-window-managers/scripts/autostart.sh &

echo -e "after autostart..."

/storage/src/dot_files/tiling-window-managers/scripts/setup-monitors.sh

echo -e "after setup-monitors..."

#BSPC Settings
bspc config border_width 4
bspc config window_gap 12
bspc config top_padding 30
bspc config bottom_padding 2
bspc config left_padding 10
bspc config right_padding 10
bspc config single_monocle false
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer false
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_slide
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

#Colors
DARK_COLOR="#000000"
ACCENT_COLOR="#9d0006"
ALERT_COLOR="#ffca3a"
bspc config normal_border_color $DARK_COLOR
bspc config active_border_color $ACCENT_COLOR
bspc config focused_border_color $ACCENT_COLOR
bspc config presel_feedback_color $ACCENT_COLOR
bspc config urgent_border_color $ALERT_COLOR

# bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a google-chrome desktop='^4' follow=on
bspc rule -a Cheatsheet state=fullscreen follow=on
bspc rule -a zoom desktop='^4' follow=on
# bspc rule -a mplayer2 state=floating center=true
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
# bspc rule -a Pavucontrol state=floating rectangle=789x512+264+130
