#!/bin/bash

if [[ $HOSTNAME == cosmos ]]; then
    echo "$(acpi -V | head -n 1 | sed s/,//g | awk '{$1=$2=$3=""; print $0}' | sed 's/ \+/ /g')"
else
    /storage/src/dot_files/tiling-window-managers/scripts/get_battery_info.sh
fi
