#!/bin/bash

if [[ $HOSTNAME == cosmos ]]; then
    # below is because it uses pipewire with pulseaudio
    RUNNING_SINK_ID="$(pactl list short sinks | grep 'RUNNING' | awk '{print $1}')"

    if [ -z "$RUNNING_SINK_ID" ]; then
        echo "No app using sound"
        exit 0
    else
        pamixer --sink "$RUNNING_SINK_ID" --get-volume-human
    fi

else
    [ "$(pamixer --get-mute)" = true ] && echo "MUTED" && exit
    pamixer --get-volume-human
fi
